config/routes.rb
Rails.application.routes.draw do
  resources :bookings, only: [:index] do
    get 'total_price', on: :collection
  end
  resources :cars do
    resources :bookings, only: %i[create]
  end
  devise_for :users
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :car
  validates :starts_at, presence: true
  validates :ends_at, presence: true
  validate :end_date_after_start_date
  validate :start_date_after_now

  def total_price
    num_days = (ends_at.to_date - starts_at.to_date).to_i + 1
    num_days * car.price_per_day
  end

  private
  def end_date_after_start_date
    return if ends_at.blank? || starts_at.blank?
    if ends_at < starts_at
      errors.add(:ends_at, "must be after the start date")
    end
  end

  def start_date_after_now
    return if starts_at.blank?
    if starts_at < Date.today
      errors.add(:starts_at, "must be after now")
    end
  end
end

app/models/car.rb
include PgSearch::Model

class Car < ApplicationRecord
  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?
  belongs_to :user
  has_one_attached :photo
  has_many :bookings, dependent: :destroy
  validates :brand, presence: true
  validates :model, presence: true
  validates :address, presence: true
  validates :price_per_day, presence: true, numericality: { greater_than: 0 }
  pg_search_scope :search_by_model_and_brand,
                against: [:model, :brand],
                using: {
                  tsearch: { prefix: true }
                }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many  :cars, dependent: :destroy
  has_many  :bookings, dependent: :destroy
  validates :email, presence: true, uniqueness: true, format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/bookings_controller.rb
# app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :set_car, only: %i[create]

  def index
    @bookings = current_user.bookings
  end

  def create
    @booking = Booking.new(booking_params)
    @booking.user = current_user
    @booking.car = @car
    if @booking.car.user == current_user
      flash[:alert] = " 🤔 You cannot book your own car !"
      redirect_to car_path(@car)
    else
      if @booking.save
        respond_to do |format|
          format.html { redirect_to car_path(@car), notice: '🥳 Booking created successfully !' }
          format.turbo_stream
        end
      else
        flash[:alert] = "😱 Failed to create booking !"
        redirect_to car_path(@car)
      end
    end
  end

  private

  def set_car
    @car = Car.find(params[:car_id])
  end

  def booking_params
    params.require(:booking).permit(:starts_at, :ends_at)
  end
end

app/controllers/cars_controller.rb
class CarsController < ApplicationController
  before_action :set_car, only: %i[show edit update destroy]

  def index
    if params[:query].present?
      @cars = Car.search_by_model_and_brand(params[:query])
    else
      @cars = Car.all
    end
  end

  def show
    @booking = Booking.new
    @marker = { lat: @car.geocode[0],
                lng: @car.geocode[1],
                info_window_html: render_to_string(partial: "info_window", locals: { car: @car })
    }
  end

  private

  def set_car
    @car = Car.find(params[:id])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  # change format
  def date_format(date)
    date.strftime('%d %b %y')
  end

  def number_to_euro(number)
    number_to_currency(number, unit: '€', separator: ',', delimiter: ' ')
  end

  def car_side_icon
    "#{icon_class('car-side')}"
  end

  def car_icon
    "#{icon_class('car')}"
  end

  def check_icon
    "#{icon_class('check')}"
  end

  def user_icon
    "#{icon_class('user')}"
  end

  def security_icon
    "#{icon_class('car-on')}"
  end
  private

  def icon_class(icon)
    "fa-solid fa-#{icon}"
  end
end

app/views/bookings/_booking.html.erb
<div class="d-flex flex-column align-items-center justify-content-center text-center mb-2 p-3 card_booking">
  <h4 class="mb-3"><strong><%= booking.car.brand %> <%= booking.car.model %></strong></h4>
  <p><strong>Starts at:</strong> <%= date_format(booking.starts_at) %></p>
  <p><strong>Ends at:</strong> <%= date_format(booking.ends_at) %></p>
  <p><strong>Total Price:</strong> <%= booking.total_price %>€</p>
</div>

app/views/bookings/create.turbo_stream.erb
<turbo-stream action="replace" target="booking_details">
  <template>
    <div class="d-flex flex-column align-items-center justify-content-center text-center mb-2 p-3 confirmation-wrapper">
      <%= content_tag(:i, ' ', class:"#{car_side_icon} fa-2x ms-4 car_move_animation")%>
      <h4>Well done ! This car is yours !</h4>
      <p><strong>Starts at:</strong> <%= date_format(@booking.starts_at) %></p>
      <p><strong>Ends at:</strong> <%= date_format(@booking.ends_at) %></p>
      <p><strong>Total Price:</strong> <%= @booking.total_price %>€</p>
      <%= link_to 'See my bookings', bookings_path, class: 'btn btn-ghost' %>
    </div>
  </template>
</turbo-stream>

app/views/bookings/index.html.erb
<p style="color: green"><%= notice %></p>

<%= link_to "Back to cars", cars_path %>
<h1 class="text-center mt-3">All My bookings</h1>

<div class="cards">
  <% @bookings.each do |booking| %>
    <%= link_to car_path(booking.car), class:"text-decoration-none" do %>
      <%= render booking %>
    <% end %>
  <% end %>
</div>

app/views/cars/_car.html.erb
  <div class="card_product d-flex flex-column p-2 m-2">
    <div class="flex-grow-0 d-flex justify-content-center align-items-center my-2"><%= content_tag(:i, ' ', class:"#{car_icon} fa-2x", id:"car")%></div>
    <div class="flex-grow-1 d-flex flex-row m-2">
      <div class="d-flex flex-column col-7">
        <div>
          <%= cl_image_tag car.photo.key, height: 300, width: 400, crop: :fill %>
        </div>
      </div>
      <div class="d-flex flex-column ms-3 justify-items-center ">
        <div class="d-flex flex-row justify-items-center mx-3"> <%= content_tag(:i, ' ', class:"#{car_icon}")%><p class="ms-2">Brand: <%= car.brand %></p></div>
        <div class="d-flex flex-row justify-items-center mx-3"> <%= content_tag(:i, ' ', class:"#{car_icon}")%><p class="ms-2">Model: <%= car.model %></p></div>
        <div class="d-flex flex-row justify-items-center mx-3"> <%= content_tag(:i, ' ', class:"#{car_icon}")%><p class="ms-2">Address: <%= car.address %></p></div>
      <div class="mt-5 d-flex">
        <h2><%= car.price_per_day %>€/day</h2>
      </div>
      </div>
    </div>
    </div>

app/views/cars/_form.html.erb
<%= simple_form_for(@car) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :brand %>
    <%= f.input :model %>
    <%= f.input :year_of_production %>
    <%= f.input :address %>
    <%= f.input :price_per_day %>
    <%= f.association :user %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/cars/_info_window.html.erb
<p><%= car.address %></p>

app/views/cars/index.html.erb
<p style="color: ocean-green"><%= notice %></p>

<div class="d-flex flex-row align-items-center justify-content-center">
  <h1>All the cars </h1>
  <%= content_tag(:i, ' ', class:"#{car_side_icon} fa-2x ms-4 car_move_animation")%>
</div>

<div class="cards">
  <% @cars.each do |car| %>
  <%= link_to car, class:"text-decoration-none" do %>
    <div class="wrapper-card">
      <%= render car %>
    </div>
  <% end %>
  <% end %>
</div>

app/views/cars/show.html.erb
<div class="mb-4">
  <%= link_to "Back to cars", cars_path, class:"text-decoration-none" %>
</div>

<div class="d-flex flex-row ms-3 justify-content-around product_info" >
  <%= render @car %>
  <div class="map ms-4" style="width: 50%; height: 100%;"
    data-controller="map" data-map-marker-value="<%= @marker.to_json %>"
    data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>">
  </div>
</div>

<%# ---------Unavailable Dates---------- %>
<% array = [] %>
<% @car.bookings.each do |booking| %>
  <% array << { from: booking.starts_at, to: booking.ends_at } %>
<% end %>
<%# ------------------------------------ %>

<div class="d-flex flex-row  ms-5" >
  <div class="car-book d-flex flex-column  mt-5 w-25">
    <%= simple_form_for([@car, @booking]) do |f| %>
      <p>When do you want to book the car ? :</p>
      <input class="form-input-select" type="string" placeholder='Select your desired dates' data-controller="datepicker" data-datepicker-array-value=<%= array.to_json %>>
      <%= f.input :starts_at, as: :hidden, input_html: { id: "start_date" } %>
      <%= f.input :ends_at, as: :hidden, input_html: { id: "end_date" } %>
      <%= f.submit 'Book' , class:'btn-ghost' %>
    <% end %>
  </div>

  <div class="d-flex justify-content-around ms-5 mt-5">
    <%= turbo_frame_tag 'booking_details' do %>
    <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>pretemoitescles</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link href="https://api.mapbox.com/mapbox-gl-js/v2.11.0/mapbox-gl.css" rel="stylesheet">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/flatpickr/dist/flatpickr.min.css">
  </head>

  <body>
    <div class="header">
      <%= render 'shared/flashes' %>
      <%= render 'shared/banner' %>
      <%= render 'shared/navbar' %>
    </div>
    <div class="content">
      <%= yield %>
    </div>
    <div class="footer">
      <%= render 'shared/footer' %>
    </div>
</html>

app/views/pages/home.html.erb
<h1 class="text-center mb-3">Welcome to Lend Me Your Keys !</h1>
<%= content_tag(:i, ' ', class:"#{car_side_icon} fa-2x ms-4 car_move_animation_slower")%>

<div class="d-flex flex-column justify-content-center align-items-center text-center card_home">
  <%= form_with url: cars_path, method: :get, local: true, class: "form-inline my-2 my-lg-0 w-50" do %>
    <%= text_field_tag :query, params[:query], class: "form-control mr-sm-2 mb-2", placeholder: "Search for cars" %>
    <%= submit_tag "Search", class: "btn btn-ghost my-2 my-sm-0" %>
  <% end %>


  <%= link_to cars_path, class:"text-decoration-none" do %>
    <div class="card_booking d-flex flex-column justify-content-center align-items-center text-center mt-4">
      <%= content_tag(:i, ' ', class:"#{car_icon} fa-2x mb-4") %>
      <h4>See all our cars</h4>
    </div>
  <% end %>
</div>

app/views/shared/_banner.html.erb
<div class="banner">
  <div class="container">
    <h1> <strong>Unlock</strong> a world of sharing with  <strong>Lend Me Your Keys</strong>!</h1>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
<div class="flash flash-success alert alert-dismissible fade show" role="alert">
  <%= notice %>
  <a data-bs-dismiss="alert" aria-label="Close">
    <i class="fas fa-times"></i>
  </a>
</div>
<% end %>
<% if alert %>
<div class="flash flash-danger alert alert-dismissible fade show" role="alert">
  <%= alert %>
  <a data-bs-dismiss="alert" aria-label="Close">
    <i class="fas fa-times"></i>
  </a>
</div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer-links">
  <a href="#"><i class="fab fa-github"></i></a>
  <a href="#"><i class="fab fa-instagram"></i></a>
  <a href="#"><i class="fab fa-facebook"></i></a>
  <a href="#"><i class="fab fa-twitter"></i></a>
  <a href="#"><i class="fab fa-linkedin"></i></a>
</div>
<div class="footer-copyright">
  This footer is made with <i class="fas fa-heart"></i> by Audrey
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%= link_to "#", class: "navbar-brand" do %>
      <%= image_tag "https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/logo.png" %>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <li class="nav-item active">
            <%= link_to "Home", root_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Cars", cars_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "My Bookings", bookings_path, class: "nav-link" %>
          </li>
          <li class="nav-item dropdown">
            <%= image_tag "https://kitt.lewagon.com/placeholder/users/ssaunier", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>